server:
  port: 8181
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: admin
        password: 123456
#配置可监控信息
management:
  #对外开放某个监控点
  endpoint:
    #health必须开
    health:
      show-details: always
      enabled: true
    #其他
    beans:
      enabled: true
  endpoints:
    #对web开启的监控点
    web:
      exposure:
        include: "*"
    #对外开放所有监控点
    enabled-by-default: true
  info:
    env:
      enabled: true


