server:
  port: 30045
spring:
  application:
    name: dandelion-mybatis-flex
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/mybatis_flex
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-flex:
  mapper-locations:
    - classpath*:/mapper/**/*.xml