version: "3.5"
services:
  nacos:
    image: nacos/nacos-server:2.0.1
    container_name: nacos
    ports:
      - 8848:8848
    environment:
      # 单机模式
      - JVM_XMS=256m
      - JVM_XMX=256m
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      # network
      - MYSQL_SERVICE_HOST=127.0.0.1
      - MYSQL_SERVICE_PORT=3306
      # https://github.com/alibaba/nacos/blob/develop/distribution/conf/mysql-schema.sql
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      - MYSQL_SERVICE_DB_PARAM="characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC"


