server:
  port: 30050
spring:
  application:
    name: dandelion-redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce: # 异步
        pool:
          max-idle: 8
          max-active: 8
          max-wait: -1
          min-idle: 0
