# 延时消息
spring:
  cloud:
    stream:
      rabbit:
        bindings:
          output:
            # 生产者配置信息
            producer:
              queueNameGroupOnly: true
              delayed-exchange: true # 开启延时队列
          input:
            # 消费者配置信息
            consumer:
              # 消息确认模式   具体查看AcknowledgeMode
              acknowledge-mode: manual
              queueNameGroupOnly: true
      bindings:
        output: #通道的名称
          destination: delay_exchange #要使用的exchange名称
          content-type: application/json
          binder: delay-rabbit
        input: #通道的名称
          destination: delay_exchange #要使用的exchange名称
          content-type: application/json
          binder: delay-rabbit
          group: delay_queue # 要使用的消息队列名称
      binders:
        delay-rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: bbb
                port: 10019
                username: root
                password: root
                virtual-host: /


